export const text = {
  "wat u zoekt":
    "U zoekt een bedrijf dat mileubewust is op zijn dienstverlening. Dat net als u bewust is op het realiseren van uw doelstellingen. Dat klantgericht werkt aan goed schoon op een betere manier. Dat goed luistert naar uw behoefte én doorvraagt tot duidelijk is wat nodig is. Dat u ontzorgt met professioneel, betrokken maatwerk tegen scherpe prijzen. Steeds meer organisaties kiezen voor Schoonmaak Loont zijn mileubewuste dienstverlening. Ook onze visie op innovatie is hierbij van doorslaggevend belang.",
  particulier:
    "De privéruimte van ons appartement en huis is een delicate sfeer, als professionals met ervaring begrijpen we heel goed dat het, naast een perfecte schoonmaak, ook belangrijk is dat mensen die deze activiteit uitvoeren zich aanpassen aan het dagelijkse ritme de harmonie van stilte in huis niet verstoren. Wij bieden een keuze uit drie reinigingspakketten: Basispakket, Extra en Renovatiepakket. Wij zorgen altijd voor details zoals het verwijderen van stof en vuil van lichtschakelaars, contacten, hoeken en plinten. We reinigen deuren en kozijnen. We letten er goed op geen strepen op het gereinigde glas en spiegeloppervlakken achter te latenBij het reinigen van de badkamer reinigen wij naast het reinigen van sanitair, sanitair en vloeren, tegelwanden en badkamerkasten aangebracht. Onze reinigingsmiddelen laten een speciale beschermlaag achter op de gereinigde oppervlakken, waardoor vuil ondanks waterdamp en stof in mindere mate gebruikt dan bij gewone middelen. De basisreiniging van de keuken omvat: het wassen van werkbladen, kastfronten, externe apparaten (spoelbak, kookplaat, oven, koelkastdeur, magnetron, waterkoker) en de vloer. Wij zorgen ook voor de netheid van het gebied rond de vuilnisbak, gooien het afval weg na het schoonmaken en het vullen van de zakken in alle containers thuis aan. We reinigen alle soorten bijkeuken, garages en balkons die worden gevonden - dit is te vinden in het Extra pakket. Tijdens het gesprek kan de exacte omvang van de werkzaamheden worden bepaald, terwijl alle werkzaamheden volgens de opgestelde lijst worden uitgevoerd.",
  particulier2:
    "Wij bieden professionele schoonmaakdiensten terwijl u rusten. Iedereen weet hoe omslachtig de renovatie is. Niet alleen duurt het meestal een zeer lange tijd, het moet nog worden opgeruimd na het. Om u extra stress en tijd te besparen komen wij u te hulp. De prijs van de na renovatie bestaat uit vele factoren. Allereerst is de M2 van het appartement belangrijk. Een ander belangrijk punt is de reikwijdte van het werk dat zojuist heeft plaatsgevonden. Het is bekend dat als het een alge- mene renovatie was, het veel meer tijd zal kosten om het appartement op orde te brengen. Het is ook niet mogelijk om de tijd te vergelijken met de lengte van de standaard reiniging. Schoonmaken na renovatie vereist veel meer precisie. Vloeren vereisen meestal herpacentificatie en wassen meerdere malen om het gewenste effect te bereiken. Meestal omvat de omvang van de service ook het Ramenpakket. Ramen vereisen wassen, maar ook het verwijderen van sporen van verf uit frames en ramen. Hoe dan ook, elk appartement is anders en het is onmogelijk om van te- voren te bepalen hoeveel tijd het kost om het schoon te maken. Je hoeft je er niet mee bezig te houden, wij doen het voor je.",
  zakelijk:
    "Als u op zoek bent naar een betrouwbaar en eerlijk bedrijf dat zal zorgen voor een uitgebreide netheid van uw kantoor tot aan de kleinste details, dan zal u geïnteresseerd zijn in ons aanbod.",
  "Waarom wij?":
    "Kantoorreiniging is onze specialiteit. We realiseren ons hoeveel een schoon, goed onderhouden kantoor uw werkcomfort beïnvloedt. Daarom behandelen we elke klant uitzonderlijk en benaderen we elke bestelling met volledige toewijding om de kleinste details te verzorgen. We zijn geobsedeerd door klantenservice, zodat u er zeker van zijn dat het werken met ons een puur plezier zal zijn, en uw kantoren zullen altijd worden opgeruimd om uw werk in comfortabele omstandigheden te garanderen.",
  "Hoe maken we schoon?":
    "Kantoorreiniging vindt plaats tijdens klantvriendelijke uren. We kunnen zowel in de kantooruren als in de uren voor de opening van het kantoor of na de sluiting schoonmaken. We reinigen 24 uur per dag, zodat de klant kan kiezen voor handige uren schoonmaken kantoren.",
  " ":
    "Voor schoonmaakkantoren hebben we alleen gecontroleerde en vertrouwde mensen in dienst die gewetensvol zijn gebleken in de uitvoering van schoonmaakdiensten. We hebben een Basispakket en een Primium pakket voor u, waar we uitgebreid met uw hele bedrijf omgaan. Op verzoek van de klant kunnen wij het kantoor voorzien van schoonmaakmiddelen en hygiëneproducten, en wij zorgen ook voor de externe ruimte voor uw bedrijf en wij hebben van het aanbieden van raamreiniging het Ramenpakket De reikwijdte van de verantwoordelijkheden moet uiteraard worden bepaald bij de opstelling van de waardering.",
  "raam pakket":
    "Ramen zijn ons bezoek en moet er onberispelijk uitzien, en schone ramen zijn een determinant van zorg voor orde. Gewassen ramen, kozijnen en vensterbanken maken de ruimte natuurlijker licht en de werkplek maakt een betere indruk. Bovendien werkt het verlichte kantoor beter en zijn schone ramen meer gezondheidszorg. Wilt u dat de ramen in uw kantoren perfect schoon zijn?  Wij zijn professionals en we hebben al duizenden ramen gerooid. We weten hoe we de werktechnieken op de bestelling kunnen afstemmen. Bij het schoonmaken van ramen houden we de kantoren stil en proberen we de schoonmaak zo soepel mogelijk te laten verlopen. Wij besteden speciale zorg in de buurt van kantoorapparatuur en documenten. U bent er zeker van zijn dat we het schoonmaakwerk van uw kantoren niemand zouden verstoren.",
  "  ":
    "We wassen allerlei ramen, waaronder plastic, aluminium, houten en oude raamramen (losgeschroefd). We zullen ook bereiken voor de dakramen en schoonmaken van de balkonramen, evenals alle andere beglazing in uw huis. We zullen leiden tot de gloed van een standaard bevuild venster voor kerstmis of zich te ontdoen van moeilijk te verwijderen onzuiverheden na renovatie. Wij voeren eenmalige en terugkerende bestellingen uit van individuele en zakelijke klanten. De prijs wordt altijd individueel bepaald op basis van de afmetingen van de ramen, het toegankelijkheidsgemak, het type beglazing en de mate van vervuiling.",
}

export const disclaimer = {
  disclaimer: [
    {
      title: "Gegevens op onze website",
      paragraphs: [
        "Schoonmaak Loont v.o.f. besteedt de grootst mogelijke zorg aan de betrouwbaarheid en actualiteit van de gege- vens op haar website. Echter kan Schoonmaak Loont v.o.f. niet verantwoordelijk worden gehouden voor enige on- volledige of onjuiste informatie die middels deze website gevonden wordt. Gebruik van enige informatie verkregen via deze website is voor eigen risico van de gebruiker.",
        "Schoonmaak Loont v.o.f. is niet aansprakelijk voor schade als gevolg van onvolledige of onjuiste informatie, noch voor schade als gevolg van problemen, veroorzaakt door het verspreiding van informatie via het internet. Ook is Schoonmaak Loont v.o.f. niet aansprakelijk voor storingen, onderbrekingen, fouten of vertraging die optreden bij het verstrekken van informatie of diensten.",
        "Tevens aanvaardt Schoonmaak Loont v.o.f. geen aansprakelijkheid voor eventuele schade die geleden wordt als gevolg van het gebruik van gegevens, adviezen of ideeën verstrekt door of namens Schoonmaak Loont v.o.f. via deze website.",
      ],
    },
    {
      title: "Hyperlinks op en naar onze website",
      paragraphs: [
        "Deze website bevat (hyper)links naar websites van andere organisaties en instellingen. Daarnaast worden vanuit andere websites links gelegd naar deze website. Schoonmaak Loont v.o.f. aanvaardt geen enkele aansprakelijkheid voor de inhoud van deze (gelinkte) websites. Dergelijke (hyper)links zijn slechts opgenomen voor uw informatie en gemak hiervan, dat betekent niet dat op of via deze websites aangeboden informatie producten of diensten door Schoonmaak Loont v.o.f. worden aanbevolen. Het gebruik van een hyperlink is volledig op eigen risico.",
        "Zonder voorafgaande schriftelijke toestemming van Schoonmaak Loont v.o.f. is het niet toegestaan links naar onze website te plaatsen.",
      ],
    },
    {
      title: "Informatie op website en berichtgeving",
      paragraphs: ["Indien informatie die op de website is opgenomen ook schriftelijk wordt verstrekt, zal in geval van tekstverschillen de schriftelijke versie bepalend zijn. Schoonmaak Loont v.o.f. garandeert niet dat aan haar toegezonden e-mails of andere elektronische berichten tijdig worden ontvangen en verwerkt en aanvaardt geen aansprakelijkheid voor ge- volgen van het niet of te laat ontvangen of verwerken daarvan."]
    }
  ],
}
